### ISSUE TITLE
Possibility to include a script tag only for the static build? 

### ISSUE THREAD

**Issue by ingvoo** [fvsch/kirby-staticbuilder#21] opened 2016-11-08 12:08 UTC
Is it possible to have some markup only executed on in the static build? In my case I need host the kirby version for admin purpose as well as the static version for production. I would like to have a tracking code only on the static enviroment. Is this somehow doable? I did see this mentioned on the [best practises page](https://github.com/fvsch/kirby-staticbuilder/blob/master/doc/static.md#knowing-when-were-rendering-a-static-page) but for me it seems that the constant `'STATIC_BUILD'` does not exist.
Thanks.

**Comment by fvsch** [comment] 2016-11-10 08:29
This should be working, I’ll look into it.

Note that for tracking scripts, if you want to restrict it to a given domain you can do that in JS:

``` js
<script>if (window.location.hostname==='my.domain.tld') {
  // add analytics
}</script>
```

I tend to do that for Google Analytics because it doesn’t filter hits depending on the hostname, and I’ve had my pages (with tracking code) copied and modified, which led to visitors for a different website showing up in my stats.

**Comment by ingvoo** [comment] 2016-11-10 10:28
Yes I actually did that with javascript. But it ends up being a little bit fragile if the site will be moved. Placing a PHP condition for including only on a build would be awesome and cleaner for the frontend. The 'STATIC_BUILD' constant is maybe not capable of this?

**Comment by fvsch** [comment] 2016-11-13 23:38
What version of the Kirby and of this plugin are you using?
Tested successfully on both Kirby 3.3.2 and 3.4.0, in a template:

``` php
<?php
if (defined('STATIC_BUILD')) {
    echo "Template: detected a static build<br>\n";
} else {
    echo "Template: not a static build<br>\n";
}
?>
```

It’s also working, as far as I could test, in snippets and in controllers.

**Comment by fvsch** [comment] 2017-03-01 11:30
Closing as I could not reproduce.

**Closed as completed by fvsch** 2017-03-01 11:30 UTC
